name: Release with Commitizen

on:
  push:
    branches:
      - master

permissions:
  contents: write   # needed to push tags & changelog
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    container:
      image: python:3.12

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - name: Bump version
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: CHANGELOG.md
          # no_raise: 21
          tags: true
        run: |
          echo "version=$(cz version --short)" >> $GITHUB_OUTPUT
          z --no-raise 21 bump --yes --changelog --changelog-to-stdout --dry-run >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: steps.cz.outputs.version != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.cz.outputs.version }}
          name: ${{ steps.cz.outputs.version }}
          body_path: CHANGELOG.md
